version: '3.8'

services:
  flask:
    build: ./app
    container_name: flask-prod

  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html

  api:
    entrypoint: ["/app/entrypoint.dev.sh"]
    build: ./django-api
    container_name: django-api
    environment:
      - APP_PORT=8000
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-api:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./django-api/.env
    ports:
      - "8000:8000"
    # depends_on:
    #   - nginx

  blog-front:
    entrypoint: ["/app/entrypoint.dev.sh"]
    build:
      context: ./django_blog_front
    container_name: blog-front
    environment:
      - APP_PORT=8500
    command: python manage.py runserver 0.0.0.0:8500
    volumes:
      - ./django_blog_front:/app
      - static_blog_volume:/app/static/
    ports:
      - "8500:8500"
    depends_on:
      - api

  # django-emails:
  #   build:
  #     context: ./django-emails
  #   container_name: django_emails
  #   env_file:
  #     - ./django-emails/.env
  #   restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"   # estebanmartins.com.ar
      - "8081:81"   # portfolio
      - "8082:82"   # globosaz
      - "8083:83"   # Blog
      - "8084:84"   # Test portfolio
    volumes:
      -  static_blog_volume:/static:ro
      - ./nginx/Lonely:/usr/share/nginx/Lonely
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/frontend-static:/usr/share/nginx/frontend-static
      - ./nginx/blog-static:/usr/share/nginx/blog-static
      - ./nginx/static-root:/usr/share/nginx/html:ro
    depends_on:
      - flask
      - php
      # - api

volumes:
  static_volume:
  media_volume:
  static_blog_volume: