version: '3.8'

volumes:
  static_blog_volume:
  static_volume:
  media_volume:

services:
  flask:
    build: ./app
    container_name: flask-prod
    env_file:
      - ./app/.env

  # php:
  #   build: ./php
  #   container_name: php-fpm
  #   volumes:
  #     - ./php:/var/www/html


  api:
    build: ./django-api
    container_name: django-api
    environment:
      - APP_PORT=8000
    volumes:
      - ./django-api:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "8000:8000"

  blog-front:
    build: ./django_blog_front
    container_name: blog-front
    environment:
      - APP_PORT=8500
    volumes:
      - ./django_blog_front:/app
      - static_blog_volume:/app/static/
    ports:
      - "8500:8500"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/logs:/var/log/nginx
      - static_blog_volume:/static:ro  # Nginx accede a estáticos del blog
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/frontend-static:/usr/share/nginx/frontend-static
      - ./nginx/static-root:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask
      - blog-front