version: '3.8'

services:
  flask:
    build: ./app
    container_name: flask-prod

  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html

  api:
    build: ./django-api
    container_name: django-api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django-api:/app
      - static_volume:/app/static/
      - media_volume:/app/media/
      # - ./django-api/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    # depends_on:
    #   - nginx

  # django-emails:
  #   build:
  #     context: ./django-emails
  #   container_name: django_emails
  #   env_file:
  #     - ./django-emails/.env
  #   restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"   # estebanmartins.com.ar
      - "8081:81"   # portfolio
      - "8082:82"   # globosaz
      - "8083:83"   # Blog
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/frontend-static:/usr/share/nginx/frontend-static
      - ./nginx/blog-static:/usr/share/nginx/blog-static
      - ./nginx/static-root:/usr/share/nginx/html:ro
    depends_on:
      - flask
      - php
      # - api
volumes:
  static_volume:
  media_volume: