version: '3.8'

services:
  flask:
    build: ./app
    container_name: flask-prod

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8090:80"
      - "9443:443"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static-root:/usr/share/nginx/html:ro
      - ./nginx/static-root-bkp:/usr/share/nginx/html1:ro
    depends_on:
      - flask
