version: '3.8'

services:
  flask:
    build: ./app
    container_name: flask-prod

  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"   # estebanmartins.com.ar
      - "8081:81"   # portfolio
      - "8082:82"   # globosaz
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/frontend-static:/usr/share/nginx/frontend-static
      - ./nginx/static-root:/usr/share/nginx/html:ro
    depends_on:
      - flask
      - php
