version: '3.8'

services:
  flask:
    build: ./app
    container_name: flask-prod

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static-root:/usr/share/nginx/html:ro      
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask
