version: '3.8'

services:
  flask:
    build: ./app
    container_name: flask-prod

  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./php:/var/www/html

  api:
    build: ./django-api
    container_name: django-api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django-api:/app
      - static_volume:/app/static/
      # - ./django-api/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/logs:/var/log/nginx
      - static_volume:/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/frontend-static:/usr/share/nginx/frontend-static
      - ./nginx/blog-static:/usr/share/nginx/blog-static:ro
      - ./nginx/static-root:/usr/share/nginx/html:ro      
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flask
      - php
volumes:
  static_volume: