# Generated by Django 4.2.21 on 2025-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='IMAGES/'),
        ),
    ]
